Feature/ipehr 144 directory
bsn-si/IPEHR-gateway pull request #141
Opened 2023-01-04 07:18 UTC by Setest

2023-01-04 10:20 UTC, SealTV requested changes
left some comments

2023-01-04 10:20 UTC, SealTV commented on src/pkg/api/directory.go
> +	}
`user_id` should be checked by `auth` middleware and here you always have valid `user_id`. You can remove all checks for `UserID`

2023-01-04 10:20 UTC, SealTV commented on src/pkg/api/directory_test.go
> +				i.EXPECT().GetEhrUUIDByUserID(gomock.Any(), gomock.Any(), gomock.Any()).Return(nil, errors.ErrNotFound)
Don't use `gomock.Any()` everywhere! You just hide mistakes, it can lead to unexpected problems in real app

2023-01-04 10:20 UTC, SealTV commented on src/pkg/helper/finder.go
> +}
just `return h.ehrUUID == ehrUUID.String()`

2023-01-09 10:13 UTC, SealTV approved these changes

2023-01-16 07:14 UTC, 1db1 requested changes

2023-01-16 07:14 UTC, 1db1 commented on src/pkg/docs/service/directory/directory.go
> +	txHash, err := s.Infra.Index.DeleteDoc(ctx, ehrUUID, types.Composition, &baseDocumentUIDHash, objectVersionID.VersionBytes(), userPrivKey, nil)
why Composition?

2023-01-16 07:14 UTC, 1db1 commented on src/pkg/api/api.go
>  	compositionService := composition.NewCompositionService(
why not just pass docService as usual?

2023-01-16 07:46 UTC, Setest commented on src/pkg/docs/service/directory/directory.go
> +	txHash, err := s.Infra.Index.DeleteDoc(ctx, ehrUUID, types.Composition, &baseDocumentUIDHash, objectVersionID.VersionBytes(), userPrivKey, nil)
My mistake

2023-01-16 08:10 UTC, 1db1 approved these changes

2023-01-16 08:13 UTC, merged